### ISSUE TITLE
Clipboard option for html and jupyter does not return full doc

### ISSUE THREAD

**Issue by ejm714** [drivendataorg/deon#34]
`clipboard` option only calls `.render`, not `.write`, meaning that clipboard paired with html or jupyter will not return the full document (i.e. will not be the same as what is returned with `output`).

For example
- `ethics-checklist -f html` only returns the html starting with `<h1>` (excludes `doc_template`). 
- `ethics-checklist -f jupyter` only return the json starting with `cell_type` (excludes `blank_jupyter_notebook`).

**Comment by pjbull** [comment]
I'm fine with changing this, but for posterity, IIRC this was a design decision.

If someone wants the checklist on the clipboard, we thought it most likely to be going into existing documents, and in that case wouldn't want the full document representation.

**Comment by jayqi** [comment]
Hm, this doesn't feel quite as sensible to me for the Jupyter format, as you'd paste the markdown into a notebook instead of editing raw json. However, I can see how this could be a useful thing with the HTML format. 

At the risk of introducing too much complexity, one possibility is that we could add a flag that let's one specify they want content only, rather than a full document.
