### ISSUE TITLE
Create 'ethics checklist' badge for projects to display

### ISSUE THREAD

**Issue by brylie** [drivendataorg/deon#79]
Is was mentioned in the  [podcast.__init__ episode on Deon](https://www.podcastinit.com/deon-with-emily-miller-and-peter-bull-episode-184/), projects commonly display badges to indicate various achievements and status reports. It was suggested that we create a badge for the Deon ethics checklist, that may be (proudly) displayed in project READMEs and websites. To that end, please consider the following badge ideas:

A) ![ethics checklist: included brightgreen](https://img.shields.io/badge/ethics%20checklist-included-brightgreen.svg?style=popout-square) (bright green, popout-square)

B) ![ethics checklist included blue](https://img.shields.io/badge/ethics%20checklist-included-blue.svg) (blue, default)

C) ![ethics checklist: complete green](https://img.shields.io/badge/ethics%20checklist-complete-brightgreen.svg) (bright green, default)

**Comment by brylie** [comment]
The configuration options are:

- left side text (e.g. ethics checklist)
- right side text (e.g. included)
- right side color (e.g. bright green)

**Comment by pjbull** [comment]
Amazing, thanks @brylie!

IMO, (A) looks the best, and instead of `included` let's put the word `deon` in the green box instead.

For a PR, we would need:
 (1) Adding how-to to the documentation: https://github.com/drivendataorg/deon/blob/master/docs/md_templates/_common_body.tpl
 (2) Adding this to the default checklist formarts for markdown and HTML: https://github.com/drivendataorg/deon/blob/master/deon/formats.py
 (3) Rebuild the docs with the `make build` command to pick up the changes.

**Comment by pjbull** [comment]
You probably need to run `pip install -r dev-requirements.txt` first so that `pytest-coverage` is installed.
